controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

     # Publish all joint states -----------------------------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Effort Group Controller ---------------------------------------
    joint_group_effort_controller:
      type: effort_controllers/JointGroupEffortController

joint_group_effort_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
