name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --repository=. --verbose=2 --recursive .
  
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install ARM compilers
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
    - name: Build and install libsockcanpp
      run: |
        cd third_party/libsockcanpp
        cmake --toolchain ../../tools/armhf-toolchain.cmake -Bbuild
        sudo cmake --build build --parallel --target install
        cd -
    - name: config
      run: >-
        cmake
        -Bbuild        
    - name: build
      run: cmake --build build --parallel
    - name: install
      run: sudo cmake --install build

  build_ros2:
    runs-on: ubuntu-22.04
    container:
      image: amd64/ros:humble
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install ARM compilers
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
      - name: Build and install libsockcanpp
        run: |
          cd third_party/libsockcanpp
          cmake --toolchain ../../tools/x86_64-toolchain.cmake -Bbuild
          sudo cmake --build build --parallel --target install
          cd -
      - name: Build and install huron
        run: |
          cmake -DBUILD_TYPE=x86_64 -Bbuild
          sudo cmake --build build --parallel --target install
      - name: build and test ROS 2
        run: |
          cd ros2/
          . /opt/ros/humble/setup.sh
          colcon build
