name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --repository=. --recursive .
  
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install ARM compilers
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
    - name: config
      run: >-
        cmake
        -Bbuild        
    - name: build
      run: cmake --build build --parallel
