name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --repository=. --verbose=2 --recursive .
  
  build_pi3_ubuntu22_arm64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: uraimo/run-on-arch-action@v2.6.0
      name: Install dependencies
      with:
        arch: none
        distro: none
        base_image: arm64v8/ros:humble
        githubToken: ${{ github.token }}
        shell: /bin/bash
        install: |
          apt-get update
          apt-get install -y gcc-aarch64-linux-gnueabihf g++-aarch64-linux-gnueabihf libeigen3-dev build-essential ros-humble-pinocchio
        run: |
          export PATH=/opt/openrobots/bin:$PATH
          export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages:$PYTHONPATH 
          export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
  
          #Install libsockcanpp
          cd /huron
          cd third_party/libsockcanpp
          cmake -DCMAKE_TOOLCHAIN_FILE=../../tools/arm64-toolchain.cmake -DBUILD_SHARED_LIBS=ON -Bbuild
          cmake --build build --parallel --target install

          #Build huron
          cd -
          export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib
          cmake -DBUILD_TYPE=arm64 -Bbuild
          cmake --build build --parallel
          cd build && ctest
          make install

  build_ros2:
    runs-on: ubuntu-22.04
    container:
      image: amd64/ros:humble
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libeigen3-dev ros-humble-pinocchio
      - name: Build and install libsockcanpp
        run: |
          cd third_party/libsockcanpp
          cmake --toolchain ../../tools/x86_64-toolchain.cmake -DBUILD_SHARED_LIBS=ON -Bbuild
          sudo cmake --build build --parallel --target install
          cd -
      - name: Build, test, and install huron
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:$LD_LIBRARY_PATH
          cmake -DBUILD_TYPE=x86_64 -DUSE_PINOCCHIO=1 -Bbuild
          cmake --build build --parallel
          cd build
          ctest
          sudo make install
          cd -
      - name: build and test ROS 2
        run: |
          cd ros2/
          . /opt/ros/humble/setup.sh
          colcon build
