name: Doxygen on GitHub Pages

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'doc'
          doxyfile-path: './Doxyfile'
          enable-latex: false

      - name: Deploy under current release version folder
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html
          destination_dir: doc/${{  github.ref_name }}
